apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: logsigner
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/trillian/logsigner@sha256:8bab3f1b605dc645a4bc5d0cd9a8c67c5a6b5f7df3bb2162d0e4b3c0571dc08c
        name: container-image
        resources: {}
status: {}
