apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: logsigner
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/trillian/logsigner@sha256:43c63c722705e6674554fb489e1666f2524b2ec422e7d2783020f014d2b53712
        name: container-image
        resources: {}
status: {}
