apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: logsigner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: logsigner
    app.kubernetes.io/part-of: trillian
  name: logsignerxufr
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: logsigner
    weight: 100
status: {}
