apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: logsigner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: logsigner
    app.kubernetes.io/part-of: trillian
  name: logsigner
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: logsigner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: logsigner
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/trillian/logsigner@sha256:407833d0eb4e2678867338292963497185df5bf081dbb58980f2fa335ab86d3f
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
