apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: logsigner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: logsigner
    app.kubernetes.io/part-of: trillian
  name: logsigner
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: logsigner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: logsigner
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tdalton-tenant/trillian/logsigner@sha256:8bab3f1b605dc645a4bc5d0cd9a8c67c5a6b5f7df3bb2162d0e4b3c0571dc08c
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
